baseURL = "https://gowreesh-mago.github.io/hava_website/"
languageCode = "en"
title = "HAVA-Lab"
disableKinds = ["RSS", "taxonomy", "term"]

[params]
  description = "Human-Aligned Video AI Laboratory - UvA Data Science Centre"
  ogImage = "/media/og-image.jpg"
  location = "University Library Singel, Amsterdam"
  contactEmail = "c.g.m.snoek@uva.nl"
  # Maximum number of upcoming events on the home page
  eventsOnHome = 4

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Mission"
    pageRef = "/mission"
    weight = 2
  [[menu.main]]
    name = "Team"
    pageRef = "/team"
    weight = 3
  [[menu.main]]
    name = "Publications & News"
    pageRef = "/publications"
    weight = 4
  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 5
  [[menu.main]]
    name = "Media"
    pageRef = "/media"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
